trigger:
  branches:
    include:
      - main

variables:
  location: 'west-us'
  acrHostName: 'spiderwebdemoregistry.azurecr.io'
  acrName: 'spiderwebdemoregistry'
  rgName: 'SpiderWebResources'
  feImageName: 'demofrontend'
  beImageName: 'demobackend'


stages:
- stage: BuildAndTest
  jobs:
    - job: RunTests
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: restore
            projects: '**/*.csproj'
        
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            command: build
            projects: '**/*.csproj'

        - task: DotNetCoreCLI@2
          displayName: 'dotnet test'
          inputs:
            command: test
            projects: 'src/*.Tests/*.csproj'
          
        - task: Docker@2
          displayName: 'docker build frontend'
          inputs:
              command: buildAndPush
              repository: $(acrHostName)
              dockerfile: src/SpiderWeb.FrontEnd/dockerfile
