version: '3'

services:
  licensing_api:
    container_name: licensing_api
    build: ./src/SpiderWeb.LicensingApi
    env_file:
      - ./src/SpiderWeb.LicensingApi/.env

  front_end:
    container_name: front_end
    build: ./src/SpiderWeb.FrontEnd
    ports:
      - 80:80
    volumes:
      - ./src/SpiderWeb.FrontEnd/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/SpiderWeb.FrontEnd/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - licensing_api